### ISSUE TITLE
画面の文字をタップすると画面下部にグーグルの検索結果が出てくる

### ISSUE THREAD

**Issue by foriver4725** [PROJECT-PIPLUP/lounas#195]
### バグの詳細

同上
仕様だったら使いにくいのでなくしてほしいです

### ブラウザの種類

Chrome

### ブラウザのバージョン

Chrome 117.0.5938.153

### 行動規範 (Code of Conduct)

- [X] このプロジェクトの行動規範に同意します。

**Comment by wiyco** [comment]
ご報告ありがとうございます！

> 画面の文字をタップすると画面下部にグーグルの検索結果が出てくる

現在、こちらの現象を検証中です。
問題のスクリーンショットをいただけると非常に助かります🙏
何卒よろしくお願いします🙇

**Comment by foriver4725** [comment]
一日開けて検証したら「長押ししたら」，でした。GO!がたまに反応しなくて困っていたのですが，気持ちチョン押ししたら問題なく使えました。
お騒がせしました。

**Comment by wiyco** [comment]
- #203
