### ISSUE TITLE
[Bug]: おすすめ結果が0件としか出てこない

### ISSUE THREAD

**Issue by Chrono5-EXH** [PROJECT-PIPLUP/lounas#197]
### バグの詳細

0件としか出てこない

### ブラウザの種類

Chrome

### 行動規範 (Code of Conduct)

- [X] このプロジェクトの行動規範に同意します。

**Comment by wiyco** [comment]
ご報告ありがとうございます！

先程対応いたしました！

何卒よろしくお願いします🙇‍♂️
